language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
    - composer self-update
    - composer --prefer-source --dev install

script:
    - ./vendor/bin/phpunit -v

after_script:
    - ./vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
